model_name_or_path: openlm-research/open_llama_13b
data_path: ~/disk2/data/sft_dataset_v0/sft_dataset_229k.json
bf16: true
output_dir: ~/disk2/workspace/llm_finetune
num_train_epochs: 3
per_device_train_batch_size: 8
per_device_eval_batch_size: 32
gradient_accumulation_steps: 2
evaluation_strategy: "steps"
eval_steps: 10000
save_strategy: "steps"
save_steps: 1500
save_total_limit: 1
learning_rate: 2e-5
weight_decay: 0.0
warmup_ratio: 0.04
lr_scheduler_type: "cosine"
logging_steps: 1
fsdp: "full_shard auto_wrap offload"
fsdp_transformer_layer_cls_to_wrap: "LlamaDecoderLayer"
tf32: true
model_max_length: 3072
gradient_checkpointing: true
dataloader_num_workers: 8