model_name_or_path: openlm-research/open_llama_13b
data_path: 
bf16: true
output_dir: "output_vicuna_13b"
num_train_epochs: 3
per_device_train_batch_size: 4
per_device_eval_batch_size: 32
gradient_accumulation_steps: 4
evaluation_strategy: "steps"
eval_steps: 1500
save_strategy: "steps"
save_steps: 1500
save_total_limit: 8
learning_rate: 2e-5
weight_decay: 0.0
warmup_ratio: 0.04
lr_scheduler_type: "cosine"
logging_steps: 1
fsdp: "full_shard auto_wrap offload"
fsdp_transformer_layer_cls_to_wrap: "LlamaDecoderLayer"
tf32: true
model_max_length: 3072
gradient_checkpointing: true