model_name_or_path: "openlm-research/open_llama_13b"
data_path: "/mnt/disks/disk2/data/sft_dataset_v0/sft_dataset_229k.json"
bf16: true
output_dir: "/mnt/disks/disk2/workspace/llm_finetune"
num_train_epochs: 3
per_device_train_batch_size: 8
per_device_eval_batch_size: 16
gradient_accumulation_steps: 4
evaluation_strategy: "steps"
eval_steps: 200
save_strategy: "steps"
save_steps: 200
save_total_limit: 3
learning_rate: 3e-4
weight_decay: 0.0
warmup_step: 200
lr_scheduler_type: "cosine"
logging_steps: 5
#fsdp: "full_shard auto_wrap offload"
#fsdp_transformer_layer_cls_to_wrap: "LlamaDecoderLayer"
tf32: true
model_max_length: 3072
gradient_checkpointing: true
dataloader_num_workers: 5
deepspeed: "/mnt/disks/disk2/workspace/llm_finetune/LongChat/longchat/train/configs/deepspeed_config.json"
num_data: 65000